//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustyLadder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tl_materials()
        {
            this.tl_project_materials = new HashSet<tl_project_materials>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public string tl_materialscol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tl_project_materials> tl_project_materials { get; set; }
    }
}
