
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrustyLadder.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tl_projects
{

    public int id { get; set; }

    public Nullable<int> customerid { get; set; }

    public Nullable<int> serviceaddressid { get; set; }

    public Nullable<int> customerserviceaddressid { get; set; }

}

}
