//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustyLadder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tl_project_materials
    {
        public int id { get; set; }
        public Nullable<int> materialid { get; set; }
        public Nullable<int> projectid { get; set; }
    
        public virtual tl_materials tl_materials { get; set; }
        public virtual tl_projects tl_projects { get; set; }
    }
}
