

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrustyLadder.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TLDBEntities : DbContext
{
    public TLDBEntities()
        : base("name=TLDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tl_customers> tl_customers { get; set; }

    public virtual DbSet<tl_project_materials> tl_project_materials { get; set; }

    public virtual DbSet<tl_serviceaddresses> tl_serviceaddresses { get; set; }

    public virtual DbSet<tl_services> tl_services { get; set; }

    public virtual DbSet<tl_materials> tl_materials { get; set; }

    public virtual DbSet<tl_states> tl_states { get; set; }

    public virtual DbSet<tl_projects> tl_projects { get; set; }

}

}

